# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digits.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, digitsDialog):
        digitsDialog.setObjectName("digitsDialog")
        digitsDialog.resize(1041, 498)
        self.btn_cap = QtWidgets.QPushButton(digitsDialog)
        self.btn_cap.setGeometry(QtCore.QRect(620, 40, 121, 41))
        self.btn_cap.setObjectName("btn_cap")
        self.btn_rec = QtWidgets.QPushButton(digitsDialog)
        self.btn_rec.setGeometry(QtCore.QRect(620, 260, 121, 31))
        self.btn_rec.setObjectName("btn_rec")
        self.cap_label = QtWidgets.QLabel(digitsDialog)
        self.cap_label.setGeometry(QtCore.QRect(120, 100, 461, 321))
        self.cap_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.cap_label.setText("")
        self.cap_label.setTextFormat(QtCore.Qt.AutoText)
        self.cap_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cap_label.setObjectName("cap_label")
        self.img_label = QtWidgets.QLabel(digitsDialog)
        self.img_label.setGeometry(QtCore.QRect(620, 80, 341, 171))
        self.img_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.img_label.setText("")
        self.img_label.setTextFormat(QtCore.Qt.AutoText)
        self.img_label.setPixmap(QtGui.QPixmap(":/images/cat.jpg"))
        self.img_label.setScaledContents(True)
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.label = QtWidgets.QLabel(digitsDialog)
        self.label.setGeometry(QtCore.QRect(620, 290, 351, 181))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(digitsDialog)
        self.label_2.setGeometry(QtCore.QRect(320, 60, 71, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(digitsDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 440, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(digitsDialog)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 440, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(digitsDialog)
        self.btn_cap.clicked.connect(digitsDialog.capture)
        self.btn_rec.clicked.connect(digitsDialog.rec)
        self.pushButton_3.clicked.connect(digitsDialog.openvideo)
        self.pushButton_4.clicked.connect(digitsDialog.closeEvent)
        QtCore.QMetaObject.connectSlotsByName(digitsDialog)

    def retranslateUi(self, digitsDialog):
        _translate = QtCore.QCoreApplication.translate
        digitsDialog.setWindowTitle(_translate("digitsDialog", "手写数字识别GUI"))
        self.btn_cap.setText(_translate("digitsDialog", "抓取图片"))
        self.btn_rec.setText(_translate("digitsDialog", "识别"))
        self.label.setText(_translate("digitsDialog", "显示结果"))
        self.label_2.setText(_translate("digitsDialog", "视频窗口"))
        self.pushButton_3.setText(_translate("digitsDialog", "开启摄像头"))
        self.pushButton_4.setText(_translate("digitsDialog", "关闭摄像头"))
